# see docs/python-linting.md for more details
repos:
    # python import sorting - will amend files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
          - id: isort

    # python code formatting - will amend files
    - repo: https://github.com/ambv/black
      rev: 21.7b0
      hooks:
          - id: black
            language_version: python3

    # automatic python syntax upgrades
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.23.3
      hooks:
          - id: pyupgrade
            language_version: python3

    # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-docstrings", "flake8-bandit", "flake8-print"]
            exclude: tests|migrations

    # python static type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
            args:
              - --ignore-missing-imports
              # means we only get error on the current file
              - --follow-imports=silent
